version: '3.5'

services:
  php-fpm:
    container_name: fx_php_fpm
    build:
      context: ./php-fpm
    volumes:
      - /root/lemp/web_peacock:/var/www/html
    restart: always

  nginx:
    container_name: fx_nginx
    build:
      context: ./nginx
    volumes:
      - /root/lemp/web_peacock:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8881:80"
      - "8882:443"
    restart: always
    depends_on:
      - php-fpm

  database:
    container_name: fx_database
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    restart: always
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8088:80
    restart: always
    environment:
        PMA_HOST: database
    depends_on:
        - database
